name: login_dash_animation
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  simple_animations:
  page_transition:
  google_maps_flutter: 
  location: 
  flutter_polyline_points: ^0.1.0
  get_it:
  url_launcher:
  font_awesome_flutter:
  google_maps_webservice:  
  flutter_sliding_tutorial:   
  curved_navigation_bar:
  local_auth:  
  firebase_auth:
  country_pickers:
  flushbar:
  firebase_core:
  http:
  shared_preferences: 
  fluttertoast: ^3.1.2
  image_cropper: 
  image_picker: 
  path_provider: 
  scoped_model: ^1.0.1
  image:  
  scroll_to_index:
  flutter_bloc:  
  circular_profile_avatar: 
  flutter_easyloading:  
  charts_flutter:
  flutter_circular_chart:
  sweetalert:
  modal_progress_hud:
  geolocator:
  flutter_slidable:         
  google_map_polyline:
  permission:  
  search_map_place: 
  validators:  
  country_code_picker: ^1.2.4
  pin_code_fields: ^2.3.0+3
  google_fonts: ^0.3.9
  place_picker: 
  flutter_typeahead:
  uuid: 
  provider: 
  liquid_progress_indicator:
  mime:
  toast:  
  flutter_rating_bar: ^3.0.0+1
  flutter_calendar_carousel: ^1.4.10
  flutter_html: ^0.11.0
  fl_chart: ^0.1.5
  flutter_webview_plugin: 0.3.9+1
  auto_size_text: ^2.1.0
  webview_flutter: ^0.3.16
  json_annotation: ^3.0.1
  sliding_up_panel: ^0.3.6
  material_design_icons_flutter: ^3.2.3695
  permission_handler: ^4.0.0
  dropdown_formfield:
  datetime_picker_formfield: ^0.1.1
  dropdownfield:
  firebase_messaging:
  flutter_local_notifications: ^1.4.4+4
  background_fetch: ^0.5.1
  workmanager: ^0.2.3
  pull_to_refresh: ^1.6.1
  connectivity: ^0.4.9+3


    

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
